#!/usr/bin/env python
"""
 All top level screens.  Screens are comprised of Frames

 v1.0 Baloothebear4 Mar 2026


"""


from pyvisualiser import *
PI = 3.14159265358979323846


class VUTestScreen(Frame):   # comprises volume on the left, spectrum on the right
    @property
    def title(self): return 'Analogue VU Meters, Roon Album Art, Metadata and progress bar'

    @property
    def type(self): return 'Test'

    def __init__(self, platform):
        back = {'image':'carbonfibre.jpg', 'per_frame_update':False, 'opacity': 255}
        Frame.__init__(self, platform, background=back, theme= 'meter1', padding=30)
  
        NEEDLE    = { 'width':4, 'colour': 'foreground', 'length': 0.8, 'radius_pc': 1.0 }
        ENDSTOPS  = (3*PI/4, 5*PI/4)  #Position of endstop if not the edge of the frame
        PIVOT     = -0.5
        OUTLINE   = {'colour':'foreground', 'width':5, 'opacity': 255, 'radius': 10}
        BACK      = {'colour':'dark', 'opacity':10, 'glow':True}
        # self += MetaImages(self  , (0.25, 0.93),align=('right','middle'))
        # self += MetaImages(self  , (0.3, 0.3),align=('centre','top'))
        # self += MetaDataFrame(self  , scalers=(0.3, 1.0), align=('centre','middle'))
        # # self += MetaImages(self  , scalers=(1.0,1.0),align=('centre','middle'), opacity=40)
        # # self += PlayProgressFrame(self  , scalers=(0.3, 0.05), align=('centre','bottom'))
        # self += VUMeter(self  ,  'left', scalers=(0.3, 0.9), align=('left','top'), pivot=PIVOT, arcs={}, endstops=ENDSTOPS, needle=NEEDLE,outline=OUTLINE) #, background='mid')
        # self += VUMeter(self  ,  'right', scalers=(0.3, 0.9), align=('right','top'), pivot=PIVOT, arcs={}, endstops=ENDSTOPS, needle=NEEDLE,outline=OUTLINE) #,background='mid')
        cols = ColFramer(self, padpc=0.05)
        cols += VUMeter(cols  ,  'left', square=False, pivot=PIVOT, arcs={}, endstops=ENDSTOPS, needle=NEEDLE,outline=OUTLINE, background=BACK)
        cols += MetaDataFrame(cols,padding=0, background=None)#,outline=OUTLINE)
        cols += VUMeter(cols  ,  'right', square=False, pivot=PIVOT, arcs={}, endstops=ENDSTOPS, needle=NEEDLE,outline=OUTLINE, background=BACK)
